import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Online Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to online Assessment</h1>

        <h1>Links for testing application</h1>
        <Link href="/">home</Link>
        <Link href="/aboutus">aboutus</Link>
        <Link href="/contactus">contactus</Link>
        <Link href="/notifications">notifications</Link>
        <Link href="/notifications/1254">notifications/1254</Link>
        <Link href="/notifications/list">notifications/list</Link>
        <Link href="/blog">blog</Link>
        <Link href="/blogs/year2022/may/5">blogs/year2022/may/5</Link>
        <Link href="/events">events</Link>
        <Link href="/events/4">events/4</Link>

      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
}
